--- #YAML:1.0
name:                Sub-SingletonBuilder
version:             0.01
abstract:            a singleton subroutine builder
license:             ~
author:              
    - Kazuho Oku
generated_by:        ExtUtils::MakeMaker version 6.44
distribution_type:   module
requires:     
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
